Ingest:
  filepath: inputs/ee_hierarchy.csv
  group_variable: gen
  group_target_val: Female
  group_other_val : Male
  outcome_variable: outcome
  outcome_target_val: hired
  outcome_other_val: not_hired
  grpers: {job_title: analyst}

StatsTesting2x2Cont:
  testing: gender
  process: hiring
  alpha: 0.05
  phi_bin_edges:
    - -1
    - -0.5
    - -0.10
    - 0.10
    - 0.5
    - 1
  phi_bin_labels:
    - very low
    - low
    - around zero
    - moderate
    - high